name: Publish yew package(s)

permissions:
  contents: write

on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:
    inputs:
      level:
        description: "Version Level major|minor|patch"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      packages:
        description: "List of packages to publish (space separated)"
        required: true
        type: string

jobs:
  publish:
    name: Publish yew
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.YEWTEMPBOT_TOKEN }}"
          fetch-depth: 0

      - name: Config Git
        uses: oleksiyrudenko/gha-git-credentials@v2.1.1
        with:
          token: "${{ secrets.YEWTEMPBOT_TOKEN }}"

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install cargo binary dependencies
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-release
          version: =0.23.1

      - name: Cargo login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Build command
        shell: bash
        env:
          PACKAGES: ${{ github.event.inputs.packages }}
        run: |
          if [[ "${{ github.event.inputs.packages }}" == "" ]]; then
            packages="yew yew-macro yew-router yew-router-macro yew-agent yew-agent-macro" # publish all the crates
          else
            packages="${{ github.event.inputs.packages }}"
          fi
    
          output=""
          for pkg in $packages
          do
            output+="--package $pkg " 
          done
          echo "pkg=$output" >> $GITHUB_ENV

      - name: Inputs
        shell: bash
        run: |
          if [[ "${{ github.event.inputs.level }}" == "" ]]; then
            echo "level=minor" >> $GITHUB_ENV
          else
            echo "level=${{ github.event.inputs.level }}" >> $GITHUB_ENV
          fi

      - name: Build changelog generator
        run: cargo build --release -p changelog -- 

      - name: Write changelog
        shell: bash
        id: changelog
        run: |
          ./target/release/changelog yew minor -t ${{ secrets.GITHUB_TOKEN }} -f "$(pwd)/CHANGELOG.md"
          ./target/release/changelog yew-router minor -t ${{ secrets.GITHUB_TOKEN }} -f "$(pwd)/CHANGELOG.md"
          ./target/release/changelog yew-agent minor -t ${{ secrets.GITHUB_TOKEN }} -f "$(pwd)/CHANGELOG.md"

      - name: Release yew
        run: cargo release ${{ env.level }} --execute --no-confirm ${{ env.pkg }}

      - name: Get tag
        id: gettag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      
      - name: Website version
        run: |
          npm install
          npx docusaurus docs:version "${{ steps.gettag.outputs.tag }}"
        working-directory: website

      - name: Commit and push website changes
        run: git add . && git commit -m "version website"
        working-directory: website

      - name: Create a version branch
        if: env.level != 'patch'
        uses: peterjgrainger/action-create-branch@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.gettag.outputs.tag }}

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.YEWTEMPBOT_TOKEN }}
          tag_name: ${{ steps.gettag.outputs.tag }}
          body: ${{ steps.changelog.outputs.stdout }}
          
